### ISSUE TITLE
Add metrics for shisui

### ISSUE THREAD

**Issue by GrapeBaBa** [optimism-java/shisui#162]
Since basic sub networks are ready, we should add metrics such as other clients to make shisui more observable.
We need first try to summary what metrics we should record and reuse geth metrics to implement it.

**Comment by r4f4ss** [comment]
I will split this issue in two tasks: implement the metrics collector with web server and integration with influx and influxV2 (geth do the same and is teh reference) and latelly decide wich metrics will be part of shisui, import existing ones from geth and possibly create new ones
