### ISSUE TITLE
[Proposal] Replace log trace strings to easily readable

### ISSUE THREAD

**Issue by r4f4ss** [optimism-java/shisui#184]
# Rationale

Geth use short, intuitive and easy to read and recognise log trace messges like:

```
>> PING/V5
<< PONG/V5
<< PING/V5
>> PONG/V5
```

When the log refer to DiskV5 Shisui also inherit those logs from geth, but logs specifically to portal wire protocol have messages non intuitive and hard to read and recognise:

```
Received ping response
Received pong response
```

# Proposal

This issue propose to substitute the following strings in file portal_protocol.go in order to facilitate visualization and log analysis:

| Current log string                     | New log string                      |
|----------------------------------------|-------------------------------------|
| Sending ping request                   | >> PING/\<NETWORK\>                 |
| Received ping response                 | << PONG/\<NETWORK\>                 |
| Sending find nodes request             | >> FIND_NODES/\<NETWORK\>           |
| Sending find content request           | >> FIND_CONTENT/\<NETWORK\>         |
| Sending offer request                  | >> OFFER/\<NETWORK\>                |
| Received accept response               | << ACCEPT/\<NETWORK\>               |
| Sent content response                  | >> CONTENT/\<NETWORK\>              |
| Received content response              | << CONTENT/\<NETWORK\>              |
| Received content response (ENRS)       | << CONTENT_ENRS/\<NETWORK\>         |
| Received returned content response     | << CONTENT_CONNECTION_ID/\<NETWORK\>|
| Received nodes response                | << NODES/\<NETWORK\>                |
| Received pong response                 | << PONG_RESPONSE/\<NETWORK\>        |
| received ping request                  | << PING/\<NETWORK\>                 |
| received find nodes request            | << FIND_NODES/\<NETWORK\>           |
| received offer request                 | << OFFER/\<NETWORK\>                |
| Sending pong response                  | >> PONG/\<NETWORK\>                 |
| Sending nodes response                 | >> NODES/\<NETWORK\>                |
| Sending enrs content response          | >> CONTENT_ENRS/\<NETWORK\>         |
| Sending raw content response           | >> CONTENT_RAW/\<NETWORK\>          |
| Sending connection id content response | >> CONTENT_CONNECTION_ID/\<NETWORK\>|
| Sending accept response                | >> ACCEPT/\<NETWORK\>               |
| Received offer content response        | << OFFER_CONTENT/\<NETWORK\>        |

Where \<NETWORK\> is one of the networks: history,state,bacon.

**Comment by GrapeBaBa** [comment]
Really nice proposal
